name: Build JavaScriptCore

on:
  push:

jobs:
  build:
    runs-on: macos-14-arm64

    steps:
      - uses: actions/checkout@v4
        with:
          repository: WebKit/WebKit
          ref: safari-7621.2.5.10-branch
          fetch-depth: 1

      - name: Install deps
        run: |
          brew install cmake ninja

      - name: Clean
        run: |
          rm -rf WebKitBuild

      - name: Build JSC
        run: |
          export CFLAGS="-Wno-error=macro-redefined"
          export CXXFLAGS="-Wno-error=macro-redefined"
          Tools/Scripts/build-jsc --jsc-only --release

      - name: Find binary
        run: |
          find WebKitBuild -name jsc -type f

      - uses: actions/upload-artifact@v4
        with:
          name: jsc
          path: |
            WebKitBuild/JSCOnly/Release/bin/jsc
            WebKitBuild/Release/bin/jsc